Struct::Tms -> Process::Tms
Deleted at https://github.com/ruby/ruby/commit/fee2913d0af894492542cc0ed5e45dbf00e8f8df since 3.0.

`Process.times` returns `Process::Tms` instead of `Struct::Tms` since 2.1.0.

```
% docker run -it --rm ghcr.io/ruby/all-ruby env ALL_RUBY_SINCE=ruby-1.8 ./all-ruby -e 'p Process.times.class'
ruby-1.8.0            Struct::Tms
...
ruby-2.1.0-preview1   Struct::Tms
ruby-2.1.0-preview2   Process::Tms
...
ruby-3.0.0-rc1        Process::Tms
```

`Benchmark.times` removed since 1.9.3.

```
% docker run -it --rm ghcr.io/ruby/all-ruby env ALL_RUBY_SINCE=ruby-1.8 ./all-ruby -r benchmark -e 'p Benchmark.times.class'
ruby-1.8.0            Struct::Tms
...
ruby-1.9.2-p330       Struct::Tms
ruby-1.9.3-preview1   -e:1:in `<main>': undefined method `times' for Benchmark:Module (NoMethodError)
                  exit 1
...
ruby-3.0.0-rc1        -e:1:in `<main>': undefined method `times' for Benchmark:Module (NoMethodError)
                  exit 1
```