Called method is write instead of print in display
```
% ruby -e 'port=Object.new;def port.write(o);p [:write,o];end;1.display(port)'
[:write, 1]
% ruby -e 'port=Object.new;def port.print(o);p [:print,o];end;1.display(port)'
-e:1:in `display': undefined method `write' for #<Object:0x000000017c9880> (NoMethodError)
        from -e:1:in `<main>'
```