Fix yydebug and yydebug= to instance method
yydebug and yydebug= were changed from class method to instance method
by https://github.com/ruby/ruby/commit/d5a3389886c9dc7f3492ef5369009c40d85b0f3c

```
$ ruby -v -rripper -e 'p Ripper.yydebug'
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
-e:1:in `<main>': undefined method `yydebug' for Ripper:Class (NoMethodError)

p Ripper.yydebug
        ^^^^^^^^

$ ruby -v -rripper -e 'p Ripper.new("").yydebug'
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
false
```